# Generated by Django 4.2.7 on 2023-11-03 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("katalog_buku", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BeliBuku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah_buku", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "nomor_telepon",
                    models.IntegerField(blank=True, default=62, null=True),
                ),
                ("alamat", models.TextField(blank=True, default="UI", null=True)),
                ("book_price", models.IntegerField(blank=True, null=True)),
                (
                    "metode_pembayaran",
                    models.CharField(
                        choices=[
                            ("COD", "COD (Cash on Delivery)"),
                            ("CARD", "Credit/Debit Card"),
                            ("EWALLET", "E-Wallet"),
                        ],
                        default="COD",
                        max_length=7,
                    ),
                ),
                (
                    "buku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="katalog_buku.buku",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
