# Generated by Django 4.2.6 on 2023-10-29 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('katalog_buku', '0005_auto_20231027_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeliBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_buku', models.IntegerField(blank=True, default=1, null=True)),
                ('nomor_telepon', models.IntegerField(blank=True, default=62, null=True)),
                ('alamat', models.TextField(blank=True, default='UI', null=True)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog_buku.buku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
