# Generated by Django 4.2.6 on 2023-10-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_buku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='belibuku',
            name='book_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
