# Generated by Django 4.2.6 on 2023-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beli_buku', '0002_belibuku_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='belibuku',
            name='metode_pembayaran',
            field=models.CharField(choices=[('COD', 'COD (Cash on Delivery)'), ('CARD', 'Credit/Debit Card'), ('EWALLET', 'E-Wallet')], default='COD', max_length=7),
        ),
    ]
