# Generated by Django 4.2.6 on 2023-10-29 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beli_buku', '0003_belibuku_metode_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='belibuku',
            name='tanggal_pembelian',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
