# Generated by Django 4.2.7 on 2023-11-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isbn", models.CharField(blank=True, max_length=255, null=True)),
                ("book_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "book_author",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tahun_publikasi", models.IntegerField(blank=True, null=True)),
                ("penerbit", models.CharField(blank=True, max_length=255, null=True)),
                ("url_foto_kecil", models.URLField(blank=True, null=True)),
                ("url_foto_medium", models.URLField(blank=True, null=True)),
                ("url_foto_large", models.URLField(blank=True, null=True)),
                ("book_price", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
