# Generated by Django 4.2.6 on 2023-10-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('penulis', models.CharField(max_length=255)),
                ('tahun_terbit', models.IntegerField()),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
