# Generated by Django 4.2.6 on 2023-10-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("katalog_buku", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="buku", name="image",),
        migrations.RemoveField(model_name="buku", name="judul",),
        migrations.RemoveField(model_name="buku", name="jumlah",),
        migrations.RemoveField(model_name="buku", name="penulis",),
        migrations.RemoveField(model_name="buku", name="tahun_terbit",),
        migrations.AddField(
            model_name="buku",
            name="book_author",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="buku",
            name="book_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="buku",
            name="isbn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="buku",
            name="penerbit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="buku",
            name="tahun_publikasi",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buku",
            name="url_foto_kecil",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buku",
            name="url_foto_large",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="buku",
            name="url_foto_medium",
            field=models.URLField(blank=True, null=True),
        ),
    ]
