# Generated by Django 4.2.7 on 2023-11-03 16:13

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command('loaddata', 'books.json')

class Migration(migrations.Migration):

    dependencies = [
        ("katalog_buku", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
