# Generated by Django 4.2.6 on 2023-10-26 13:03

from django.db import migrations
from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
        call_command("loaddata", "books.json")

class Migration(migrations.Migration):

    dependencies = [
        ("katalog_buku", "0002_remove_buku_image_remove_buku_judul_and_more"),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
