# Generated by Django 4.2.6 on 2023-10-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog_buku', '0003_auto_20231026_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='book_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
