# Generated by Django 4.2.6 on 2023-10-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_buku", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestbuku",
            name="author",
            field=models.CharField(
                default="Tidak diketahui", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="requestbuku",
            name="tahun_publikasi",
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name="statusrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("DITERIMA", "DITERIMA"),
                    ("DITOLAK", "DITOLAK"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
