# Generated by Django 4.2.7 on 2023-12-05 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("request_buku", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestStatusBuku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul_buku", models.CharField(max_length=100)),
                (
                    "author",
                    models.CharField(
                        default="Tidak diketahui", max_length=100, null=True
                    ),
                ),
                ("tahun_publikasi", models.IntegerField(default=-1, null=True)),
                ("isi_buku", models.TextField(default="Tidak diketahui", null=True)),
                ("tanggal_request", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("DITERIMA", "DITERIMA"),
                            ("DITOLAK", "DITOLAK"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
