# Generated by Django 4.2.6 on 2023-10-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_buku", "0002_alter_requestbuku_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestbuku",
            name="isi_buku",
            field=models.TextField(default="Tidak diketahui", null=True),
        ),
    ]
