# Generated by Django 4.2.6 on 2023-10-26 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_buku", "0002_requestbuku_isi_buku_alter_requestbuku_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestbuku",
            name="tanggal_request",
            field=models.DateField(verbose_name="date_added"),
        ),
    ]
