# Generated by Django 4.2.6 on 2023-10-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("request_buku", "0003_alter_requestbuku_tanggal_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestbuku",
            name="tanggal_request",
            field=models.DateField(auto_now_add=True),
        ),
    ]
