# Generated by Django 4.2.6 on 2023-10-27 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('katalog_buku', '0003_auto_20231026_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinjamBuku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durasi', models.IntegerField()),
                ('nomor_telepon', models.IntegerField()),
                ('alamat', models.TextField()),
                ('metode_pembayaran', models.CharField(choices=[('Debit', 'Debit'), ('Kredit', 'Kredit'), ('E-Wallet', 'E-Wallet')], default='Debit', max_length=20)),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='katalog_buku.buku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
