# Generated by Django 4.2.7 on 2023-11-29 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("katalog_buku", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PinjamBuku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("durasi", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "nomor_telepon",
                    models.IntegerField(blank=True, default=62, null=True),
                ),
                ("alamat", models.TextField(blank=True, default="UI", null=True)),
                (
                    "buku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="katalog_buku.buku",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
