# Generated by Django 4.2.6 on 2023-10-28 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinjam_buku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pinjambuku',
            name='metode_pembayaran',
        ),
    ]
