# Generated by Django 4.2.6 on 2023-10-26 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("katalog_buku", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonasiBuku",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah_donasi", models.IntegerField()),
                (
                    "buku",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="katalog_buku.buku",
                    ),
                ),
            ],
        ),
    ]
