# Generated by Django 4.2.6 on 2023-10-25 13:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('katalog_buku', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BukuDonasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donator', models.CharField(max_length=255)),
                ('donation_date', models.DateField(default=datetime.date.today)),
                ('donation_amount', models.IntegerField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='katalog_buku.buku')),
            ],
        ),
    ]