# Generated by Django 4.2.6 on 2023-10-28 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donasi_buku', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bukudonasi',
            name='book',
        ),
        migrations.AddField(
            model_name='bukudonasi',
            name='author',
            field=models.CharField(default='lebron', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bukudonasi',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='bukudonasi',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DITERIMA', 'DITERIMA'), ('DITOLAK', 'DITOLAK')], default='PENDING', max_length=15),
        ),
        migrations.AddField(
            model_name='bukudonasi',
            name='title',
            field=models.CharField(default='james', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bukudonasi',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bukudonasi',
            name='year',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
